baseURL = "https://davidhallin.com/"
languageCode = "en-us"
title = "davidhallin.com"
paginate = 20

copyright = "Â© David Hallin"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[params]
	subtitle = "a blog by david hallin about programming, and learning new things"

	avatar = "/images/dave.jpeg"
	
	featherIconsCDN = true
	favicon = "/favicon.ico"
	mode = "auto" # "dark" or "auto"
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Nav.
[menu]
    [[menu.main]]
    name = "home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 2

    [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 3

    [[menu.main]]
    name = "uses"
    url = "/uses/"
    weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/hallindavid"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[outputs]
home = ["HTML", "RSS", "JSON"]
